---
title: "Data Science Homework 6"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelr)

theme_set(theme_bw())
```

### Problem One

*importing and manipulating data* 

```{r importing and manipulating wp data, message = FALSE, warning = FALSE}
murder <- 
  read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

murder <- murder %>%  
  unite("city_state", c("city", "state"), sep = ", ") %>% 
  mutate(solved = ifelse(disposition == "Closed by arrest", 1, 0), 
         victim_race = ifelse(victim_race != "White", "non-White", "White"), 
         victim_race = fct_relevel(victim_race, "White", "non-White"),
         victim_age = as.numeric(victim_age)) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")))
```

*Logit models*

```{r baltimore logit}
balt_model <- murder %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(solved ~ victim_sex + victim_race + victim_age, family = binomial, data = .)

broom::tidy(balt_model) %>% 
  mutate(or = exp(estimate), 
         or_lower = exp(estimate - 1.96*std.error), 
         or_upper = exp(estimate + 1.96*std.error)) %>% 
  filter(term == "victim_racenon-White") %>% 
  select(or, or_lower, or_upper) %>% 
  rename("Odds ratio" = or, 
         "Lower bound" = or_lower, 
         "Upper bound" = or_upper) %>% 
  knitr::kable(digits = 3)
```

```{r out.width = "70%", fig.height = 8, fig.align = "center", dpi = 300}
murder %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(logit_solve = map(data, ~glm(solved ~ victim_sex + victim_race + victim_age, 
                                      family = binomial, data = .x)), 
         logit_solve = map(logit_solve, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() %>% 
  filter(term == "victim_racenon-White") %>% 
  mutate(or = exp(estimate), 
         or_lower = exp(estimate - 1.96*std.error), 
         or_upper = exp(estimate + 1.96*std.error), 
         city_state = fct_reorder(city_state, estimate)) %>% 
  select(city_state, or, or_lower, or_upper) %>% 
  ggplot(aes(x = city_state, y = or)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = or_lower, ymax = or_upper)) + 
  geom_hline(yintercept = 1.0, linetype = "dashed", color = "red") + 
  coord_flip() + 
  labs(y = "Odds ratio", 
       x = "City, State")
```

### Problem Two

```{r importing cleaning and checking some correlations, message = FALSE}
bweight <- read_csv("data/birthweight.csv") %>% 
  janitor::clean_names()

# sum(is.na(bweight))
# equals 0, no missing data

bweight <- bweight %>% 
  mutate(babysex = as.factor(babysex), 
         frace = as.factor(frace), 
         malform = as.factor(malform), 
         mrace = as.factor(mrace))

# dataset with only numeric variables
wt_num <- select_if(bweight, is.numeric)

corr <- list()

for (i in 1:ncol(wt_num)) {
  corr[[i]] <- cor(wt_num$bwt, wt_num[i])
}

as.data.frame(corr) %>% 
  gather(key = var, value = correlation) %>% 
  filter(abs(correlation) > 0.2)

set.seed(20)
```

```{r cross validation}
cv_bweight <- crossv_mc(bweight, 100)

cv_bweight <- cv_bweight %>% 
    mutate(hyp_mod = map(train, ~lm(bwt ~ babysex + fincome + gaweeks + parity + smoken + wtgain, data = .x)),
           cor_mod = map(train, ~lm(bwt ~ bhead + blength + gaweeks + wtgain, data = .x)), 
           comb_mod = map(train, ~lm(bwt ~ babysex + fincome + gaweeks + parity + smoken + wtgain + 
                                       bhead + blength, data = .x))) %>% 
    mutate(rmse_hyp = map2_dbl(hyp_mod, test, ~rmse(model = .x, data = .y)),
           rmse_cor = map2_dbl(cor_mod, test, ~rmse(model = .x, data = .y)),
           rmse_comb = map2_dbl(comb_mod, test, ~rmse(model = .x, data = .y)))

cv_bweight %>%  
  select(starts_with("rmse")) %>% 
  gather(key = model, value = rmse) %>% 
  mutate(model = str_replace(model, "rmse_", ""),
         model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin()
```

```{r going with comb model}
comb_mod <- bweight %>% 
  lm(bwt ~ babysex + fincome + gaweeks + parity + smoken + wtgain + bhead + blength, data = .) 

bweight %>% 
  add_predictions(comb_mod) %>% 
  add_residuals(comb_mod) %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point() + 
  geom_smooth(se = FALSE)
```

```{r comparing to jeff models}
cv_bweight2 <- crossv_mc(bweight, 100)

cv_bweight2 <- cv_bweight2 %>% 
  mutate(my_mod = map(train, ~lm(bwt ~ babysex + fincome + gaweeks + parity + smoken + wtgain + 
                                       bhead + blength, data = .x)), 
         main_mod = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)), 
         emm_mod = map(train, ~lm(bwt ~ (bhead + blength + babysex)^4, data = .x))) %>% 
  mutate(rmse_my = map2_dbl(my_mod, test, ~rmse(model = .x, data = .y)),
         rmse_main = map2_dbl(main_mod, test, ~rmse(model = .x, data = .y)),
         rmse_emm = map2_dbl(emm_mod, test, ~rmse(model = .x, data = .y)))

cv_bweight2 %>% 
  select(starts_with("rmse")) %>% 
  gather(key = model, value = rmse) %>% 
  mutate(model = str_replace(model, "rmse_", ""),
         model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin()
```













